# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Low German spellchecker"
nds = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Low German, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
nds = "TRANSLATE: A spellchecker for Low German, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.nds"

[windows]
system_product_code = "{E92F5174-AF55-4F5A-8C16-50F5A818420C}_is1"
legacy_product_codes = [
    { value = "4F7A6FD0-7CEB-4F7B-BE45-BFA8518559EC", kind = "nsis" },
    { value = "7D368711-3A40-4DCB-B6FD-BA93555BFE0F", kind = "nsis" }
]

[package.speller]
name = "Low German"
version = "0.1.1"

[package.grammar]
name = "Low German"
version = "0.1.0"

[package.tts-text-proc]
name = "Low German"
version = "0.1.0"

[package.hyphenator]
name = "Low German"
version = "0.1.0"
